# Generated by Django 3.2.8 on 2021-11-01 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='isseubook',
            name='fine',
        ),
    ]
