# Generated by Django 3.2.8 on 2021-11-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrequest',
            name='issue_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
